=== 333495/java/day030_xml/src/org/cfx/_02schema/contactsSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://ronghuanet.com" elementFormDefault="qualified">
	<xs:element name="contacts">
		<xs:complexType>
			<xs:sequence maxOccurs='unbounded'>
				<xs:element name="linkman">
					<xs:complexType>
					            <xs:sequence>
						<xs:element name='name' type='xs:string' />
						<xs:element name='email' type='xs:string' />
						<xs:element name='address' type='xs:string' />
						<xs:element name='group' type='xs:string' />
					            </xs:sequence>
						<xs:attribute name="id" type="xs:long" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== 333495/java/day030_xml/src/org/cfx/_02schema/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns="http://ronghuanet.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
	xs:schemaLocation="http://ronghuanet.com  contactsSchema.xsd">
	<linkman id="2334">
		<name>gg</name>
		<email>gg@ronghuanet.com</email>
		<address>成都</address>
		<group>蓉华教育</group>
	</linkman>
	<linkman id="45">
		<name>gg</name>
		<email>xiong@qq.com</email>
		<address>阿斯顿发送到</address>
		<group>蓉华教育</group>
	</linkman>

</contacts>
